name: game
description: An interactive scavenger hunt for the cornell campus.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sliding_up_panel: ^2.0.0+1
  velocity_x:
  flutter_blurhash:
  cached_network_image: ^3.1.0
  google_fonts: 6.1.0
  url_launcher:
  confetti: ^0.7.0
  google_sign_in: ^6.1.6
  simple_animations: ^5.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  http: ^1.1.0
  flutter_signin_button: ^2.0.0
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.2
  profanity_filter: ^2.0.0
  intl: 0.19.0
  flutter_linkify: ^6.0.0
  # platform_device_id: ^1.0.1
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  device_info_plus: ^9.1.0
  flutter_svg: ^2.0.8
  google_maps_flutter: ^2.5.3
  google_maps_flutter_android: ^2.4.2
  google_maps_flutter_platform_interface: ^2.4.3
  location: ^5.0.0
  # flutter_config: ^2.0.2
  flutter_config_plus: ^1.1.1
  dropdown_button2: ^2.3.9
  carousel_slider: ^5.0.0
  tuple: ^2.0.2
  sticky_headers: ^0.3.0+2
  win32: ^5.6.1

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/main_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Add this section to override the problematic file
dependency_overrides:
  # This forces the latest intl version that works with flutter_localizations
  intl: 0.19.0
