// CODE AUTOGENERATED BY npm run updateapi

import 'dart:async';

import 'package:game/api/game_client_dto.dart';
import 'package:socket_io_client/socket_io_client.dart';

class GameClientApi {
  final _updateUserDataController =
      StreamController<UpdateUserDataDto>.broadcast(sync: true);
  Stream<UpdateUserDataDto> get updateUserDataStream =>
      _updateUserDataController.stream;

  final _updateErrorDataController =
      StreamController<UpdateErrorDto>.broadcast(sync: true);
  Stream<UpdateErrorDto> get updateErrorDataStream =>
      _updateErrorDataController.stream;

  final _updateChallengeDataController =
      StreamController<UpdateChallengeDataDto>.broadcast(sync: true);
  Stream<UpdateChallengeDataDto> get updateChallengeDataStream =>
      _updateChallengeDataController.stream;

  final _updateEventTrackerDataController =
      StreamController<EventTrackerDto>.broadcast(sync: true);
  Stream<EventTrackerDto> get updateEventTrackerDataStream =>
      _updateEventTrackerDataController.stream;

  final _updateEventDataController =
      StreamController<UpdateEventDataDto>.broadcast(sync: true);
  Stream<UpdateEventDataDto> get updateEventDataStream =>
      _updateEventDataController.stream;

  final _updateLeaderDataController =
      StreamController<UpdateLeaderDataDto>.broadcast(sync: true);
  Stream<UpdateLeaderDataDto> get updateLeaderDataStream =>
      _updateLeaderDataController.stream;

  final _groupInvitationController =
      StreamController<GroupInviteDto>.broadcast(sync: true);
  Stream<GroupInviteDto> get groupInvitationStream =>
      _groupInvitationController.stream;

  final _updateGroupDataController =
      StreamController<UpdateGroupDataDto>.broadcast(sync: true);
  Stream<UpdateGroupDataDto> get updateGroupDataStream =>
      _updateGroupDataController.stream;

  final _updateOrganizationDataController =
      StreamController<UpdateOrganizationDataDto>.broadcast(sync: true);
  Stream<UpdateOrganizationDataDto> get updateOrganizationDataStream =>
      _updateOrganizationDataController.stream;

  final _reconnectedController = StreamController<Null>.broadcast(sync: true);
  Stream<Null> get reconnectedStream => _reconnectedController.stream;

  final _reconnectingController = StreamController<Null>.broadcast(sync: true);
  Stream<Null> get reconnectingStream => _reconnectingController.stream;

  final _connectedController = StreamController<Null>.broadcast(sync: true);
  Stream<Null> get connectedStream => _connectedController.stream;

  final disconnectedController = StreamController<Null>.broadcast(sync: true);
  Stream<Null> get disconnectedStream => disconnectedController.stream;

  void connectSocket(Socket sock) {
    sock.onReconnect((data) => _reconnectingController.add(null));
    sock.onReconnecting((data) => _reconnectedController.add(null));
    sock.onDisconnect((data) => disconnectedController.add(null));

    sock.on(
        "updateUserData",
        (data) =>
            _updateUserDataController.add(UpdateUserDataDto.fromJson(data)));

    sock.on(
        "updateErrorData",
        (data) =>
            _updateErrorDataController.add(UpdateErrorDto.fromJson(data)));

    sock.on(
        "updateChallengeData",
        (data) => _updateChallengeDataController
            .add(UpdateChallengeDataDto.fromJson(data)));

    sock.on(
        "updateEventTrackerData",
        (data) => _updateEventTrackerDataController
            .add(EventTrackerDto.fromJson(data)));

    sock.on(
        "updateEventData",
        (data) =>
            _updateEventDataController.add(UpdateEventDataDto.fromJson(data)));

    sock.on(
        "updateLeaderData",
        (data) => _updateLeaderDataController
            .add(UpdateLeaderDataDto.fromJson(data)));

    sock.on(
        "groupInvitation",
        (data) =>
            _groupInvitationController.add(GroupInviteDto.fromJson(data)));

    sock.on(
        "updateGroupData",
        (data) =>
            _updateGroupDataController.add(UpdateGroupDataDto.fromJson(data)));

    sock.on(
        "updateOrganizationData",
        (data) => _updateOrganizationDataController
            .add(UpdateOrganizationDataDto.fromJson(data)));

    _connectedController.add(null);
  }

  GameClientApi() {}
}
