/* Automatically generated by Prisma
  Warnings:

  - A unique constraint covering the columns `[username]` on the table `User` will be added. If there are existing duplicate values, this will fail.

*/
-- CreateEnum
CREATE TYPE "ChallengeTimerStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'EXPIRED', 'PAUSED', 'CANCELLED');

-- AlterTable
ALTER TABLE "Challenge" ADD COLUMN     "timerLength" INTEGER;

-- CreateTable
CREATE TABLE "ChallengeTimer" (
    "id" TEXT NOT NULL,
    "subject" TEXT NOT NULL DEFAULT 'ChallengeTimer',
    "timerLength" INTEGER NOT NULL DEFAULT 600,
    "startTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endTime" TIMESTAMP(3),
    "currentStatus" "ChallengeTimerStatus" NOT NULL DEFAULT 'ACTIVE',
    "warningMilestones" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
    "warningMilestonesSent" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
    "lastWarningSent" TIMESTAMP(3),
    "userId" TEXT NOT NULL,
    "challengeId" TEXT NOT NULL,

    CONSTRAINT "ChallengeTimer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ChallengeTimer_userId_challengeId_key" ON "ChallengeTimer"("userId", "challengeId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");

-- AddForeignKey
ALTER TABLE "ChallengeTimer" ADD CONSTRAINT "ChallengeTimer_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ChallengeTimer" ADD CONSTRAINT "ChallengeTimer_challengeId_fkey" FOREIGN KEY ("challengeId") REFERENCES "Challenge"("id") ON DELETE CASCADE ON UPDATE CASCADE;
