// CODE AUTOGENERATED BY npm run updateapi
// IF YOU MODIFY THIS FILE, MAKE SURE TO ALSO MODIFY THE updateapi SCRIPT!
// OTHERWISE YOUR CHANGES MAY BE OVERWRITTEN!

import { Socket } from "socket.io-client";
import * as dto from "../all.dto";

export class ServerApi {
  constructor(private socket: Socket) {}

  send(ev: string, data: {}) {
    console.log(`Sending ${ev} with ${JSON.stringify(data)}`);
    this.socket.emit(ev, data);
  }

  requestAchievementData(data: dto.RequestAchievementDataDto) {
    this.send("requestAchievementData", data);
  }

  updateAchievementData(data: dto.UpdateAchievementDataDto) {
    this.send("updateAchievementData", data);
  }

  requestChallengeData(data: dto.RequestChallengeDataDto) {
    this.send("requestChallengeData", data);
  }

  updateChallengeData(data: dto.UpdateChallengeDataDto) {
    this.send("updateChallengeData", data);
  }

  requestEventData(data: dto.RequestEventDataDto) {
    this.send("requestEventData", data);
  }

  requestFilteredEventIds(data: dto.RequestFilteredEventsDto) {
    this.send("requestFilteredEventIds", data);
  }

  requestRecommendedEvents(data: dto.RequestRecommendedEventsDto) {
    this.send("requestRecommendedEvents", data);
  }

  requestEventLeaderData(data: dto.RequestEventLeaderDataDto) {
    this.send("requestEventLeaderData", data);
  }

  requestEventTrackerData(data: dto.RequestEventTrackerDataDto) {
    this.send("requestEventTrackerData", data);
  }

  updateEventData(data: dto.UpdateEventDataDto) {
    this.send("updateEventData", data);
  }

  requestOrganizationData(data: dto.RequestOrganizationDataDto) {
    this.send("requestOrganizationData", data);
  }

  updateOrganizationData(data: dto.UpdateOrganizationDataDto) {
    this.send("updateOrganizationData", data);
  }

  requestAllUserData(data: dto.RequestAllUserDataDto) {
    this.send("requestAllUserData", data);
  }

  addManager(data: dto.AddManagerDto) {
    this.send("addManager", data);
  }

  onUpdateUserData(callback: (data: dto.UpdateUserDataDto) => void) {
    this.socket.removeAllListeners("updateUserData");
    this.socket.on("updateUserData", (data) => callback(data));
  }

  onUpdateErrorData(callback: (data: dto.UpdateErrorDto) => void) {
    this.socket.removeAllListeners("updateErrorData");
    this.socket.on("updateErrorData", (data) => callback(data));
  }

  onUpdateChallengeData(callback: (data: dto.UpdateChallengeDataDto) => void) {
    this.socket.removeAllListeners("updateChallengeData");
    this.socket.on("updateChallengeData", (data) => callback(data));
  }

  onUpdateAchievementData(
    callback: (data: dto.UpdateAchievementDataDto) => void
  ) {
    this.socket.removeAllListeners("updateAchievementData");
    this.socket.on("updateAchievementData", (data) => callback(data));
  }

  onUpdateAchievementTrackerData(
    callback: (data: dto.AchievementTrackerDto) => void
  ) {
    this.socket.removeAllListeners("updateAchievementTrackerData");
    this.socket.on("updateAchievementTrackerData", (data) => callback(data));
  }

  onUpdateEventTrackerData(callback: (data: dto.EventTrackerDto) => void) {
    this.socket.removeAllListeners("updateEventTrackerData");
    this.socket.on("updateEventTrackerData", (data) => callback(data));
  }

  onUpdateEventData(callback: (data: dto.UpdateEventDataDto) => void) {
    this.socket.removeAllListeners("updateEventData");
    this.socket.on("updateEventData", (data) => callback(data));
  }

  onUpdateLeaderData(callback: (data: dto.UpdateLeaderDataDto) => void) {
    this.socket.removeAllListeners("updateLeaderData");
    this.socket.on("updateLeaderData", (data) => callback(data));
  }

  onGroupInvitation(callback: (data: dto.GroupInviteDto) => void) {
    this.socket.removeAllListeners("groupInvitation");
    this.socket.on("groupInvitation", (data) => callback(data));
  }

  onUpdateGroupData(callback: (data: dto.UpdateGroupDataDto) => void) {
    this.socket.removeAllListeners("updateGroupData");
    this.socket.on("updateGroupData", (data) => callback(data));
  }

  onUpdateOrganizationData(
    callback: (data: dto.UpdateOrganizationDataDto) => void
  ) {
    this.socket.removeAllListeners("updateOrganizationData");
    this.socket.on("updateOrganizationData", (data) => callback(data));
  }

  onUpdateLeaderPosition(
    callback: (data: dto.UpdateLeaderPositionDto) => void
  ) {
    this.socket.removeAllListeners("updateLeaderPosition");
    this.socket.on("updateLeaderPosition", (data) => callback(data));
  }
}
