name: Check flutter code-style CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --file ci/flutter-format/Dockerfile -t app
