name: Dev deployment from Github to AWS
on:
  push:
    branches:
      - nirbhaysinghnarang-patch-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: nirbhaysnarang27
          password: CornellGo!2022

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: nirbhaysnarang27/cornell-go:latest
